const SET_POLL_URL = 'SET_POLL_URL';
const GET_POLL_START = 'GET_POLL_START';
const GET_POLL_SUCCESS = 'GET_POLL_SUCCESS';
const GET_POLL_FAIL = 'GET_POLL_FAIL';
const SET_POLL_ANSWER = 'SET_POLL_ANSWER';

export default {
  SET_POLL_URL,
  GET_POLL_START,
  GET_POLL_SUCCESS,
  GET_POLL_FAIL,
  SET_POLL_ANSWER,
};
